name: antbike
description: A Flutter app to control an electric vehicle.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
 
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.12
  usb_serial: ^0.4.0
  shared_preferences: ^2.0.13


flutter:
  uses-material-design: true

  assets:
    - assets/